stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
  tags:
    - docker
  stage: test
  image: python:3.10
  script:
    - export PYTHONPATH=$CI_PROJECT_DIR/src
    - pip install -r requirements.txt
    - pytest --cov=src tests/
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 week
  coverage: '/^TOTAL.*\s+(\d+%)$/'
