stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
  tags:
    - docker
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pytest --cov=src --cov-report=html --cov-report=term
  artifacts:
    paths:
      - htmlcov/
  coverage: '/\s+(\d+\%)$/'

deploy_stable:
  tags:
      - docker
  image: python:3.10
  stage: deploy
  script:
    - pip install -r requirements.txt
    - hatch build
    - echo "Contents of dist/:"
    - ls -la dist/
  only:
    - tags
