stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
  tags:
    - docker
  stage: test
  image: python:3.10
  script:
    - cd my-arithmetic-enzo/
    - pip install -r requirements.txt
    - pytest --cov=src --cov-report=html tests/
    - mv htmlcov ../htmlcov
  artifacts:
    paths:
      - htmlcov/
  coverage: '/^TOTAL.*\s+(\d+%)$/'
