sync-with-github:
  tags:
    - docker
  image: bitnami/git:latest
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - if git remote | grep -q "^github$"; then git remote remove github; fi
    - git remote add github $REMOTE_REPOSITORY_URL
    - echo "Current remotes:"
    - git remote -v
    - git checkout main
    - git pull origin main
    - git pull github main
    - git status
    - git push github HEAD:main
