concurrent = 1
check_interval = 0

[[runners]]
  name = "my-runner"
  url = "https://gitlab.univ-lr.fr/"
  token = ""
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
  [runners.cache]
